language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-30

    # Additional components
    #- extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - chmod +x ./gradlew
  - yes | sdkmanager "platforms;android-30"

stages:
  - compile
  - static_analysis

jobs:
  include:
    - stage: compile
      name: "Compile"
      script: ./gradlew build
    - stage: static_analysis
      script: ./gradlew checkstyle
      name: "Checkstyle analysis"
      script: ./gradlew pmd
      name: "PMD analysis"
      artifacts:
        name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
        expire_in: 4 days
        paths:
          - app/build/reports/

notifications:
  slack: soundrecorderteam:Nut7a5FL3Y7KkjpaJU1yhgMi
