language: android

android:
  components:
    - tools
    - platform-tools
    - android-$ANDROID_API_LEVEL
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - '.+'

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_EMULATOR_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew compileJava

notifications:
  slack: soundrecorderteam:Nut7a5FL3Y7KkjpaJU1yhgMi
