language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8
  
before_install:
  - chmod +x gradlew

notifications:
  slack:
    secure:
      soundrecorderteam:Nut7a5FL3Y7KkjpaJU1yhgMi
